mklink %HOMEPATH%"\.latexmkrc" %HOMEPATH%"\dotfiles\.latexmkrc"
mklink %HOMEPATH%"\.vimrc" %HOMEPATH%"\dotfiles\.vimrc"
mklink %HOMEPATH%"\.gvimrc" %HOMEPATH%"\dotfiles\.gvimrc"
mklink /d %HOMEPATH%"\.vim" %HOMEPATH%"\dotfiles\.vim"
mkdir %HOMEPATH%"\dotfiles\.vim\tmp"
mkdir %HOMEPATH%"\dotfiles\.vim\tmp\swp"
mkdir %HOMEPATH%"\dotfiles\.vim\tmp\bak"
