[[plugins]]
repo = 'Shougo/dein.vim'

[[plugin]]
repo = 'Shougo/deoplete.nvim'

[[plugins]]
repo = 'cespare/vim-toml'
on_ft = 'toml'

[[plugins]]
repo = 'Shougo/unite.vim'

[[plugins]]
repo = 'ujihisa/unite-colorscheme'

[[plugins]]
repo = 'tomasr/molokai'
hook_add = '''
  colorscheme molokai
  let g:molokai_original=1
  set background=dark
'''
