[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/vimproc.vim'
build = 'make'

[[plugin]]
repo = 'Shougo/deoplete.nvim'

[[plugins]]
repo = 'cespare/vim-toml'
on_ft = 'toml'

[[plugins]]
repo = 'Shougo/unite.vim'

[[plugins]]
repo = 'ujihisa/unite-colorscheme'

[[plugins]]
repo = 'tomasr/molokai'
hook_add = '''
  colorscheme molokai
  let g:molokai_original=1
  set background=dark
'''

[[plugin]]
repo = 'osyo-manga/vim-monster'

[[plugin]]
repo = 'kannokanno/previm'

[[plugin]]
repo = 'tyru/open-browser.vim'

[[plugin]]
repo = 'slim-template/vim-slim'
